### ISSUE TITLE
It's not work with Alfred 2

### ISSUE THREAD

**Issue by ghost** [Jacob87/alfred-hostsfilemanager#1]
Hi,
This workflow is very useful but not work with Alfred 2.
Please export a version that work with Alfresh 2
Thank you so much

**Comment by iOvergaard** [comment]
Support has just been added for the latest Alfred 4 with [2.0.0](https://github.com/iOvergaard/alfred-hostsfilemanager/releases/tag/2.0.0). Closing this.
